### ISSUE TITLE
read_credentials and use_credentials issue

### ISSUE THREAD

**Issue by kylelundstedt** [cloudyr/aws.signature#10]
Hi Thomas,

I just downloaded your cool `aws.signature` package, and quickly gave it a try.  As the R console output below demonstrates, there was no joy using either the `read_credentials` or `use_credentials` functions:

```
> library(aws.signature)
> packageVersion("aws.signature")
[1] ‘0.2.5’
> aws.signature::read_credentials(file = "~/.aws/credentials")
Error: 'read_credentials' is not an exported object from 'namespace:aws.signature'
```

The `canonical_request`, `signature_v2_auth`, `signature_v4`, `signature_v4_auth`, and `string_to_sign` functions are all available.  Also, I've replicated the issue on both Ubuntu 14.04 and OS X.

I don't know anything about package building, so I can't send you a pull request.  However, is it possible these functions weren't made available during your build process?

Thanks again for all of your hard work on the `cloudyr` packages!
Kyle

**Comment by leeper** [comment]
Thanks. This should now be fixed. Can you try reinstalling?

**Comment by kylelundstedt** [comment]
Works like a charm; thanks so much!
