### ISSUE TITLE
Improve checking for credentials

### ISSUE THREAD

**Issue by leeper** [cloudyr/aws.signature#11]
Add `check_for_keypair()` function that does the following:

1. Checks whether key, secret key, and session token have been specified. If so, uses them.
2. If missing, check environment variables.  If so, uses them.
3. If missing, check a central credentials file using `use_credentials()`.  If so, uses them.
4. If missing, try to assume role from EC2 metadata via:

```
get_ec2_role <- function(role) {
  if (missing(role)) {
    role <- aws.ec2metadata::metadata$iam_role_names()
    if (!length(role)) {
      stop("No IAM role profile available in instance metadata")
    }
  }
  # return role credentials as list
  aws.ec2metadata::metadata$iam_role(role[1L])
}
```

This shouldn't set environment variables because credentials are temporary, so it should simply pass them through the signing functions.

**Comment by kadrach** [comment]
This would be incredibly useful, we're running into this with SQS now as well ;)

**Comment by ananthu1834** [comment]
we're running into this as well ;)
 👍 1

**Comment by leeper** [comment]
Quick update: I'm working on a draft of this on the [`credentials-walk` branch](https://github.com/cloudyr/aws.signature/tree/credentials-walk) in the form of a `locate_credentials()` function that walks through sources of credentials in an order similar to boto (without the boto-specific configuration file sources). Any feedback welcome; I wouldn't advise using it until it's folded into master.

**Comment by alexsanjoseph** [comment]
@leeper - We have the problem as well. Your code looks great. Is it ready for master yet?

**Comment by andyhd** [comment]
Hi, we need to get credentials from the EC2 metadata IAM role, and I've written [some code that emulates how Boto handles credentials](https://github.com/ministryofjustice/aws.signature/commit/f28515fe0682e4fb331957fc0c894bfb7ba82958) which works reasonably well. Would you like me to make a PR?

**Comment by leeper** [comment]
Hi, @andyhd. Thanks. That looks pretty similar (in broad spirit) to what I have on [the `credentials-walk` branch](https://github.com/cloudyr/aws.signature/compare/credentials-walk) ([noted above](https://github.com/cloudyr/aws.signature/issues/11#issuecomment-292904991)). I'm inclined to merge in my approach but if there's something obviously missing there, which your implementation handles better, I'm happy to incorporate it.

**Comment by andyhd** [comment]
Hi @leeper - yes, I referred to your branch while writing mine. We need this right now and your branch seems not quite finished, so I'm afraid I've duplicated some of your effort!

**Comment by leeper** [comment]
This implementation has been finalized based on a slightly modified precedence for sources of credentials (see documentation).
