### ISSUE TITLE
Default R tilde expansion on Windows points to the wrong directory

### ISSUE THREAD

**Issue by kadrach** [cloudyr/aws.signature#12]
Base R on Windows:

```
> path.expand("~")
[1] "C:/Users/kadrach/Documents"
```

This causes problems [here](https://github.com/cloudyr/aws.signature/blob/8a3921a8269fa0861e08faa72c335fc3eb51487a/R/read_credentials.R#L1), as the file is generally located in `%USERPROFILE%\.aws\credentials`, e.g.  `C:\Users\kadrach\.aws\credentials`.

**Comment by leeper** [comment]
Thanks!
