### ISSUE TITLE
Parameter Store as dotfile alternative

### ISSUE THREAD

**Issue by kylelundstedt** [cloudyr/aws.signature#14]
Hi Thomas,

Great work on the 'awspack' packages.  We're using them quite a bit!
Just a thought for future development - keeping AWS creds in dotfiles has drawbacks when working with a team. The new Parameter Store in AWS Systems Manager looks like a cool alternative.

Cheers
Kyle

https://aws.amazon.com/blogs/mt/interesting-articles-on-ec2-systems-manager-parameter-store/
https://stp5.net/blog/post/secrets-in-aws/

**Comment by leeper** [comment]
Thanks, looks interesting.
