### ISSUE TITLE
parse_credentials fails to parse credentials files without spaces around equals-sign

### ISSUE THREAD

**Issue by davidski** [cloudyr/aws.signature#15]
Per https://github.com/cloudyr/aws.signature/blob/master/R/read_credentials.R#L67, `parse_credentials` is expecting key-value pairs separated by a ` = `. This causes keys without the space (i.e. `KEY=VALUE`) to fail to parse.

AWS documentation is not fully consistent on the file format with the Boto docs specifying no spaces (http://boto3.readthedocs.io/en/latest/guide/configuration.html) and some docs using the space-equals-space format.

Changing to use a regex with optional whitespace would allow both formats to function.

**Comment by leeper** [comment]
Thank you!
