### ISSUE TITLE
Support for IAM roles for ECS tasks

### ISSUE THREAD

**Issue by razvanm** [cloudyr/aws.signature#23]
A task in ECS can use a role that is different from the VMs that are part of the ECS cluster. If a task is configured with a task role then the environment variable will be populated with a `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` variable that which can be used like this to retrieve a set of temporary credentials:

    curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI

Reference: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html

**Comment by leeper** [comment]
Do you want a function to be able to grab these or do you want it to happen automatically on function calls?

**Comment by razvanm** [comment]
I would expect both `locate_credentials` to return them and also for the downstream functions (the ones from aws.s3 for example) to start working.

**Comment by leeper** [comment]
Makes sense.
