### ISSUE TITLE
Possible to get presigned URL for use in Shiny?

### ISSUE THREAD

**Issue by jennaallen** [cloudyr/aws.signature#24]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [x] a question about package functionality
 - [ ] a suggested code or documentation change, improvement to the code, or feature request

I am building a shiny app that uses images and pdf documents from a private s3 bucket. Can I use the `aws.signature` package to get a presigned URL to plug into my shiny code (see below)? I think to do this I would need to use the `signature_v4_auth` function but I am confused about how to specify the arguments (action, query_args, canonical_headers, request_body, etc.). 

If this is possible, is it secure or does it expose my key and secret?

```R
ui  <- fluidPage(
  htmlOutput("image")
)

server <- function(input, output) {

  output$image <- renderText({

    presigned_url <- signature_v4_auth(service = "s3",
                                verb = "GET", 
                                request_body = "https://s3.amazonaws.com/mybucket/myimage.png",
                                key = Sys.getenv("AWS_ACCESS_KEY_ID"),
                                secret = Sys.getenv("AWS_SECRET_ACCESS_KEY")
                              )
    paste("<img src = ",'"',presigned_url'", height = "30px">', sep = "")
   })
}
```

**Comment by leeper** [comment]
Why not just use the aws.s3 package for this? The `get_object()` function seems like what you want.

**Comment by jennaallen** [comment]
Ok, this is what I have been doing, but was unsure how to handle the raw vector type so I thought a pre-signed url might be easier to figure out.

For images, I can display them with the following using the magick package

```R
ui <- fluidPage(
  imageOutput("image")
)

server <- function(input, output) {
output$image <- renderImage({

    tmpfile <- get_object("s3://mybucket/myimage.png") %>% 
      image_read() %>% 
      image_write(tempfile(fileext = 'png'), format = 'png')
    
    # Return a list
    list(src = tmpfile, 
         height = "200px", 
         contentType = "image/png")
   })
}
```
But I am unsure how to handle pdfs, since I want to keep them in the pdf format rather than converting to an image. Do you know how I can create a pdf from the raw vector returned by get_object? I'm still googling around for this. Thanks for your help and confirming `get_object` is the right way to go.

**Comment by leeper** [comment]
You can save the raw vector locally using `writeBin()` and then handle it as you would any file.

**Comment by jennaallen** [comment]
Ok, I'll give that a try! Thanks for your help!

**Comment by leeper** [comment]
I'm closing this. Feel free to post again if there's more I can help with and I will reopen.
