### ISSUE TITLE
use_credentials get wrong secret key

### ISSUE THREAD

**Issue by jeremywzh** [cloudyr/aws.signature#25]
after I run "aws.signature::use_credentials()", it does read the information from ~/.aws/credentials. However, the secrete key string misses the last character. I don't know why. Everything else is correct, it just clip out the last character. Because of that, function like s3read_using reports an error.

I manually corrected the secrete key by using: Sys.setenv("AWS_SECRET_ACCESS_KEY"=Correct Key), everything works fine.

I think there is a bug in the "parse_credentials" function in the file "read_credentials.R"

**Comment by leeper** [comment]
Can you profile a reproducible example? For example, create a `credentials` file with some fake credentials that produces the error. The automatic testing in place does not produce this error, so I'll need more information in order to be able to bug check and apply a patch.

**Comment by jeremywzh** [comment]
It happens when there is no newline character at the end of the aws_secret_access_key

**Comment by leeper** [comment]
Again, I need a reproducible example as I don't see this in the unit tests.

**Comment by leeper** [comment]
Thank you for the reproducible example. This should now be fixed and a complete test is in place to prevent it in the future.
