### ISSUE TITLE
ECS Credentials are never* used

### ISSUE THREAD

**Issue by jon-mago** [cloudyr/aws.signature#34]
The current order of checking for EC2 then ECS credentials means that ECS credentials are never* used, as an ECS container will almost always be running on an EC2 host.  The container credentials can give a job more, or different permissions compared to the EC2 instance.

I assume this change in ordering was made as the previous ECS detection was broken (See cloudyr/aws.ec2metadata#3).  Once that is fixed, it should be possible to check for ECS credentials first, without that breaking credential discovery.  Sorry for that error.

**Comment by binary-finary** [comment]
We are stuck on this issue as well.

**Comment by jon-mago** [comment]
This should now be fixed (in the 0.5.0 release)
