### ISSUE TITLE
Seeking new maintainer!

### ISSUE THREAD

**Issue by leeper** [cloudyr/aws.signature#36]
This package is not being actively maintained. If you're interested in contributing or taking over, please express your interest here.

**Comment by jon-mago** [comment]
Hi @leeper, I would be willing to maintain this project in addition to https://github.com/cloudyr/aws.signature .

I'm sorry to hear you're no longer able to do so, but thank you for writing all of these in the first place.

**Comment by ColmanHumphrey** [comment]
hey @leeper @jon-mago, how's progress on finding a new maintainer?

**Comment by leeper** [comment]
Hi @jon-mago If you're willing to do that, please send a PR to change the maintainer field to you and I'll give you write access.

**Comment by jon-mago** [comment]
Closing this now I've merged the PR
