### ISSUE TITLE
locate_credentials bug causes failure to install on R3.5 

### ISSUE THREAD

**Issue by lissahyacinth** [cloudyr/aws.signature#39]
Possible bug in installation from Git master - I think it's due to the list in credentials_to_list 

```
return(list(key = key, secret = secret, session_token = session_token, region = region))
```

As adding in else statements with NULLs for key, secret, session_token, etc, fixes the installation. Added example on PR.

```
> remotes::install_github("cloudyr/aws.signature")
Downloading GitHub repo cloudyr/aws.signature@master
✔  checking for file ‘/private/var/folders/np/fy2_8btj5334yh48qbl9m1rm0000gq/T/Rtmpd3rB2U/remotes156fd7b6f2753/cloudyr-aws.signature-df1ddb4/DESCRIPTION’ ...
─  preparing ‘aws.signature’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘aws.signature_0.4.5.tar.gz’
   
Installing package into ‘/Users/lissa.hyacinth/Rlibs’
(as ‘lib’ is unspecified)
* installing *source* package ‘aws.signature’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘aws.signature’:
 .onLoad failed in loadNamespace() for 'aws.signature', details:
  call: credentials_to_list(cred, region = region, default_region = default_region, 
  error: object 'key' not found
Error: loading failed
Execution halted
``

**Comment by lissahyacinth** [comment]
Oops, added this to aws.signature rather than aws.secrets.

**Comment by weisisheng** [comment]
Probably breaking every rule in the book refreshing this but why would I still be getting the same error after the merge?

Tried installing from github, local .zip and CRAN. Even checked to code is the latest, line by line.

---

Error: package or namespace load failed for ‘aws.signature’:
 .onLoad failed in loadNamespace() for 'aws.signature', details:
  call: credentials_to_list(cred, region = region, default_region = default_region, 
  error: object 'key' not found
Error: loading failed
Execution halted

---
R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          6.0                         
year           2019                        
month          04                          
day            26                          
svn rev        76424                       
language       R                           
version.string R version 3.6.0 (2019-04-26)
nickname       Planting of a Tree          
>

**Comment by lissahyacinth** [comment]
@jon-mago That PR only seems to resolve issues regarding the ~/.aws/credentials file. My best guess is that you *do* have an aws credentials file, but that it doesn't have any keys in it. 

I'm also struggling to replicate the issue. Could you confirm if you have that file at that location, or if you have any of the following environmental variables by running Sys.getenv() with any of the strings below as input?
AWS_DEFAULT_REGION, AWS_SESSION_TOKEN, AWS_SECRET_ACCESS_KEY, AWS_ACCESS_KEY_ID

Obviously don't share them if you do.

**Comment by jon-mago** [comment]
Hi @lissahyacinth , I think you meant that for @weisisheng  (I just reopened it so I could keep track of new progress on a closed issue). But thank you for helping to debug this, regardless 😃

**Comment by stelsemeyer** [comment]
@jon-mago  I have trouble loading `aws.signature` in a clean R session, raising the same error as mentioned above. I hotfixed this in a fork [here](https://github.com/stelsemeyer/aws.signature/pull/1/files), not sure if this is the best way to fix it though:

**Comment by zdk123** [comment]
@lissahyacinth says:
>  My best guess is that you do have an aws credentials file, but that it doesn't have any keys in it.

This is intended in some cases. For instances, we have a series of profiles with a source profile and a role arn that should not have it's own keys. Installs of `aws.signature` are failing with the OP's error, but perfectly kosher for the aws-cli.

**Comment by jon-mago** [comment]
> @jon-mago I have trouble loading `aws.signature` in a clean R session, raising the same error as mentioned above. I hotfixed this in a fork [here](https://github.com/stelsemeyer/aws.signature/pull/1/files), not sure if this is the best way to fix it though.

I think that's the best fix I can think of.  Though looking over the code, it's not clear what purpose that `.onLoad()` actually has.  It doesn't seem to prevent any future calls to `locate_credentials()` as there's no caching of credentials that I can see, or anything like that.

Never the less, can you please submit that patch as a PR to this repo too, please?

**Comment by zdk123** [comment]
Pinging @stelsemeyer...  any change of opening a PR with your fix? I'd appreciate getting this fixed ASAP.

**Comment by jon-mago** [comment]
If not, I'll just add the changes and add a credit.

**Comment by jon-mago** [comment]
This should be fixed.  I'll get a release out soon
