### ISSUE TITLE
query parameter to signature_v4_auth assumes all queries are strings

### ISSUE THREAD

**Issue by cboettig** [cloudyr/aws.signature#5]
An acceptable query list to httr can include integers, e.g. `query = list("max-keys" = 2)`.  This causes ` signature_v4_auth` throws the relatively obscure error `Error in strsplit(URL, "") : non-character argument` even though httr is capable of handling query lists of mixed type and handles the conversions correctly.

**Comment by leeper** [comment]
The problem is [here](https://github.com/cloudyr/aws.signature/blob/master/R/v4.R#L21-L22). `utils::URLencode` apparently only accepts a character `URL` argument. Should be a simple fix to coerce the query string values to character before URL-encoding.
