### ISSUE TITLE
Add Container Credentials To Provider Chain

### ISSUE THREAD

**Issue by ryanb8** [cloudyr/aws.signature#50]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [ ] a question about package functionality
 - [x] a suggested code or documentation change, improvement to the code, or feature request

Cloudyr does not support container_providers ([boto3 class](https://github.com/boto/botocore/blob/13362410ce8aaa5d35b4ffb056c6c5a58d659bb3/botocore/credentials.py#L1792)) in its credential chain ([boto3 credential providers chain](https://github.com/boto/botocore/blob/13362410ce8aaa5d35b4ffb056c6c5a58d659bb3/botocore/credentials.py#L91-L105)).

When using a service like AWS Batch, boto3 will consume and use the permissions tied to the [AWS Batch Job Role (step 9 here)](https://docs.aws.amazon.com/batch/latest/userguide/create-job-definition.html) before using the [ECS Compute Cluster's Instance Role (step 4d here)](https://docs.aws.amazon.com/batch/latest/userguide/create-compute-environment.html). As far as I can tell, this isn't included at all in cloudyR's [`locate_credentials`](https://github.com/cloudyr/aws.signature/blob/master/R/locate_credentials.R)

Can we add this provider to the cloudyR credential chain? It looks like you just need to hit ` 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` with that environment variable expanded and get the creds: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html)

**Comment by jon-mago** [comment]
Hi @ryanb8 

This is handled in [locate_credentials](https://github.com/cloudyr/aws.signature/blob/a6520d4f8cc2a0d0d5c082997056e34792d9729d/R/locate_credentials.R#L120) which is checked before the EC2 metadata.

If this isn't working, then that's a bug and please let me know.

**Comment by ryanb8** [comment]
Closing the loop here:
- `aws.signature` requires the `aws.ec2metadata` package to access ECS metadata and access credentials from this source.
- `aws.ec2metadata` is not a dependency of `aws.signature`, but just a suggestion. Default usage of `install.packages` for installation of `aws.signature` or another package that requires `aws.signature` WILL NOT install `aws.ec2metadata`.
- `aws.signature` silently skips this provider on the credential chain if the `aws.ec2metadata` package is not found.'

It sounds nice to me to post a warning if one of those env vars are present but those packages aren't, but I know how to fix my problem and that's good enough for me.

**Comment by jon-mago** [comment]
That's a fair call on (some kind of) warning, especially as a "once on package load"
