### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by dworzanski** [cloudyr/aws.signature#6]
There is no license provided for this excellent work (or any of the Cloudyr projects I looked at). Please consider a GPL or BSD/MIT license. Thank you.

**Comment by leeper** [comment]
R packages include license information in the DESCRIPTION file rather than a separate LICENSE file. All cloudyr packages are GPL-licensed.

**Comment by dworzanski** [comment]
Okay, thanks. Sorry about the bug -- I'm not too experienced with R.

**Comment by leeper** [comment]
No worries!
