### ISSUE TITLE
Authorization for API Gateway Request

### ISSUE THREAD

**Issue by wpenglish** [cloudyr/aws.signature#60]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [O] a question about package functionality
 - [ ] a suggested code or documentation change, improvement to the code, or feature request

Hello! I am new to R and I am trying to write some functionality for others to use AWS API Gateway. I was wondering if you would be able to provide an example or some direction for getting authorization needed for a GET Request using httr. What functions would I use to get the correct signature for the request?

```R
R
key <- "FAKEKJKJBDKEY"
secret <- "FAKELKJLKSJSLKJSKEY"
region <- "us-east-2"
t <- format(Sys.time(),"%Y%m%dT%H%M%SZ", tz = "UTC")
signed <- signature_v4_auth(
  datetime = t,
  service = "execute-api",
  verb = "GET",
  action = "/test/demo/nameOfFile.json",
  canonical_headers = list(
    "Host"= 'fakehost-api.us-east-1.amazonaws.com',
    "X-AMZ-Date"=t
  ),
  request_body = "",
  signed_body=TRUE,
  key = key,
  secret= secret,
  region = region
)

response <- GET(url = "https://fakehost-api.us-east-1.amazonaws.com/test/demo/nameOfFile", add_headers(signed))
```

Thank you!

**Comment by jon-mago** [comment]
Unfortunately there isn't (yet) a nice and easy method for getting all the of headers and such you'd need in a format which can be added via `add_headers`.  So I think you'd have to do something like:

```
headers <- c(
   "X-AMZ-Date"=t,
   "Host"= 'fakehost-api.us-east-1.amazonaws.com',
  "X-AMZ-Content-Sha256"= signed$BodyHash,
  "Authorization"= glue::glue_data(signed, "{Algorithm} Credential={Credential},SignedHeaders={SignedHeaders},Signature={Signature}")
)
response <- GET(url = "https://fakehost-api.us-east-1.amazonaws.com/test/demo/nameOfFile", add_headers(headers))
```

**Comment by wpenglish** [comment]
Thank you! I think I am getting closer. When I add in the code provided at get a "400 Bad Request", which is something I have yet to see when trying to GET in any environment with this API.

**Comment by jon-mago** [comment]
Great!  Was that format correct, or did you have to things?

**Comment by wpenglish** [comment]
It was correct! Thank you!

**Comment by wpenglish** [comment]
I was wrong, I didn't do full testing. I accidentally only tested on ones that didn't need authentication. I am now getting ""The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.". I haven't had time to look into what is different, but I will soon
